### ISSUE TITLE
async-http-client version 2.10.4 security issues

### ISSUE THREAD

**Issue by pmologni** [cloudbees/zendesk-java-client#330]
**Describe the bug**
current async-http-client version 2.10.4 have 2 [High Severity security issues](https://snyk.io/test/github/cloudbees/zendesk-java-client)

Can you please bump it the the latest version?

https://snyk.io/test/github/AsyncHttpClient/async-http-client

Cheers,
Paolo

**Comment by aheritier** [comment]
Hi @pmologni 

  AFAICS 2.10.4 is the latest release available and deployed on Maven central cc @slandelle

  My understanding of https://snyk.io/test/github/cloudbees/zendesk-java-client is that the issue is in netty and not async-http-client 

* https://snyk.io/vuln/SNYK-JAVA-IONETTY-543669
* https://snyk.io/vuln/SNYK-JAVA-IONETTY-543490

  I proposed an update of the dependency in async-http-client : https://github.com/AsyncHttpClient/async-http-client/pull/1694

**Comment by pmologni** [comment]
Thanks @aheritier!

**Comment by aheritier** [comment]
@slandelle merged the PR but it is useless in our context. These security issues are on the server side of Netty. async-http-client is using the client side.
